const data = {
  products: [
    {
      __id: 1,
      name: 'apple watch',
      category: 'watch',
      image: '/img/product-2.jpg',
      price: 120,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 1299,
      description: 'The future is on your wrist.',
    },
    {
      __id: 2,
      name: 'Sony headphone',
      category: 'headphone',
      image: '/img/product-5.jpg',
      price: 99,
      brand: 'Sony',
      rating: 4,
      numReviews: 869,
      description: 'high quality headphone',
    },
    {
      __id: 3,
      name: 'Nike shoe',
      category: 'shoe',
      image: '/img/product-7.jpg',
      price: 139,
      brand: 'Nike',
      rating: 4,
      numReviews: 2551,
      description: 'high quality street shoe',
    },
    {
      __id: 4,
      name: 'amazon echo',
      category: 'electronics',
      image: '/img/product-11.jpg',
      price: 179,
      brand: 'amazon',
      rating: 5,
      numReviews: 136,
      description: 'high quality home product',
    },
    {
      __id: 5,
      name: 'apple air pod',
      category: 'air pod',
      image: '/img/product-19.jpg',
      price: 189,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 7524,
      description: 'high quality headphone',
    },
  ],
};

export default data;
